name: test-macOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test-macOS:

    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx envinfo
    - run: npm install
    - run: npm run ci
