name: test-linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  test-linux:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
    - uses: actions/checkout@v4
    - name: Install Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npx envinfo
    - run: npm install
    - run: npm run ci
